# Generated by Django 4.2.10 on 2024-02-16 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0004_alter_post_title_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='My Freaking Blog!', max_length=255),
        ),
    ]
