# Generated by Django 4.2.10 on 2024-02-28 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0011_alter_post_snippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_header',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
